In [1]:
import numpy as np

In [2]:
a=np.arange(1,5)
a

array([1, 2, 3, 4])

In [3]:
a+10

array([11, 12, 13, 14])

In [4]:
a-5

array([-4, -3, -2, -1])

In [5]:
a

array([1, 2, 3, 4])

In [6]:
a*2

array([2, 4, 6, 8])

In [7]:
a**2

array([ 1,  4,  9, 16])

In [8]:
a%2

array([1, 0, 1, 0], dtype=int32)

In [9]:
a/3

array([0.33333333, 0.66666667, 1.        , 1.33333333])

In [11]:
a

array([1, 2, 3, 4])

In [13]:
b=np.arange(1,5)
a

array([1, 2, 3, 4])

In [14]:
b

array([1, 2, 3, 4])

In [15]:
a+b

array([2, 4, 6, 8])

In [17]:
c=np.arange(1,10)
c

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
c.shape

(9,)

In [20]:
x=np.array([[1,2,3],[4,5,6]])
x

array([[1, 2, 3],
       [4, 5, 6]])

In [21]:
y=np.array([[1,2,3],[4,5,6]])
y

array([[1, 2, 3],
       [4, 5, 6]])

In [22]:
x+y

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [23]:
x-y

array([[0, 0, 0],
       [0, 0, 0]])

In [24]:
z=np.array([1,2])
z.shape

(2,)

In [25]:
x.shape

(2, 3)

In [26]:
z+x

ValueError: operands could not be broadcast together with shapes (2,) (2,3) 

In [27]:
z=np.array([1,2,3])
z.shape

(3,)

In [28]:
x+z

array([[2, 4, 6],
       [5, 7, 9]])