In [2]:
import numpy as np

In [3]:
arr =np.array(1)
arr

array(1)

In [4]:
arr=np.array(2)
arr

array(2)

In [5]:
arr.ndim

0

In [6]:
a=np.array([1,2,3])
a

array([1, 2, 3])

In [7]:
a.ndim

1

In [8]:
li=[1,2,3,4]
b=np.array(li)
b

array([1, 2, 3, 4])

In [9]:
tu=(1,2,3,4,5,6,7,8,9,10)
c=np.array(tu)
c

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [10]:
d=np.array((1,2,3,4,5,6))
d

array([1, 2, 3, 4, 5, 6])