In [1]:
import numpy as np

In [2]:
a=np.array([3,4,5,6])
a

array([3, 4, 5, 6])

In [3]:
b=np.array([13,14,15,16])
b

array([13, 14, 15, 16])

In [4]:
np.concatenate((a,b))

array([ 3,  4,  5,  6, 13, 14, 15, 16])

In [5]:
c=np.concatenate((a,b))
c

array([ 3,  4,  5,  6, 13, 14, 15, 16])

In [6]:
a

array([3, 4, 5, 6])

In [7]:
np.append(a,100)

array([  3,   4,   5,   6, 100])

In [9]:
a=np.append(a,100)

In [10]:
a

array([  3,   4,   5,   6, 100])

In [11]:
b=np.array([[1,2],[3,4]])
b

array([[1, 2],
       [3, 4]])

In [12]:
np.append(b,[[10],[20]],axis=1)

array([[ 1,  2, 10],
       [ 3,  4, 20]])

In [13]:
b=np.append(b,[[10],[20]],axis=1)

In [14]:
b

array([[ 1,  2, 10],
       [ 3,  4, 20]])