In [1]:
import numpy as np
a=np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [2]:
a.dtype

dtype('int32')

In [3]:
a=np.array([1,2,3,4,5],dtype="int")
a

array([1, 2, 3, 4, 5])

In [4]:
a=np.array([1,2,3,4,5],dtype="float")
a

array([1., 2., 3., 4., 5.])

In [5]:
a.dtype

dtype('float64')

In [6]:
a=np.array([1,2,3,4,5],dtype="complex")
a

array([1.+0.j, 2.+0.j, 3.+0.j, 4.+0.j, 5.+0.j])

In [7]:
a.dtype

dtype('complex128')

In [9]:
b=np.array([[1,2,3],[4,5,6]],dtype="float")
b

array([[1., 2., 3.],
       [4., 5., 6.]])

In [10]:
b.dtype

dtype('float64')