In [1]:
import numpy as np

In [2]:
a=np.array([[1,2],[3,4]])
a

array([[1, 2],
       [3, 4]])

In [3]:
b=np.array([[11,12],[13,14]])
b

array([[11, 12],
       [13, 14]])

In [4]:
c=a.dot(b)
c

array([[37, 40],
       [85, 92]])