In [28]:
import numpy as np

In [29]:
a=np.array([[1,2],[3,4],[5,6]])
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [30]:
a.flatten()

array([1, 2, 3, 4, 5, 6])

In [31]:
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [32]:
b=a.flatten()
b

array([1, 2, 3, 4, 5, 6])

In [33]:
b[0]=5
b

array([5, 2, 3, 4, 5, 6])

In [34]:
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [35]:
a.flatten()

array([1, 2, 3, 4, 5, 6])

In [39]:
c=a.ravel()
c

array([1, 2, 3, 4, 5, 6])

In [40]:
c[0]=5
c

array([5, 2, 3, 4, 5, 6])

In [41]:
a

array([[5, 2],
       [3, 4],
       [5, 6]])