In [15]:
import numpy as np

In [16]:
x=np.arange(1,10)
x

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
index = np.array([1,5,7])
index

array([1, 5, 7])

In [18]:
x[index]

array([2, 6, 8])

In [19]:
b=np.array([[1,2,3],[4,5,6],[7,8,9]])
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [20]:
b[[0,2]]

array([[1, 2, 3],
       [7, 8, 9]])

In [21]:
b[[0,2],[1]]

array([2, 8])

In [22]:
x

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
m=x[[1,4,1,4,1,4]]

In [24]:
m

array([2, 5, 2, 5, 2, 5])

In [25]:
x=np.array([[1,-2,3],[4,-5,-9]])


In [26]:
x[x<0]

array([-2, -5, -9])

In [27]:
x[x<0]*-1

array([2, 5, 9])

In [28]:
x[x<0]*-2

array([ 4, 10, 18])

In [29]:
x[x<0]**2

array([ 4, 25, 81])