In [16]:
import numpy as np

In [17]:
a=np.array([[1,2],[3,4],[5,6]])
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [18]:
a[1][1]

4

In [19]:
a[2][0]


5

In [20]:
a[0][0]


1

In [21]:
a[0][1] = 1000
a

array([[   1, 1000],
       [   3,    4],
       [   5,    6]])

In [22]:
b=np.array([[1,2,3],[4,5,6],[7,8,9]])
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [23]:
b[2][2]

9

In [24]:
a

array([[   1, 1000],
       [   3,    4],
       [   5,    6]])

In [25]:
a[-1][-2]

5