In [1]:
import numpy as np

In [2]:
a=np.array([10,54,6,58,23,14])
a

array([10, 54,  6, 58, 23, 14])

In [3]:
a.sum()

165

In [4]:
a.prod()

60510240

In [5]:
a.mean()

27.5

In [7]:
a.max()

58

In [8]:
a.min()

6

In [10]:
a.argmax()

3

In [11]:
a.argmin()

2

In [12]:
b=np.array([[10,20,30],[40,50,60],[80,100,5]])
b

array([[ 10,  20,  30],
       [ 40,  50,  60],
       [ 80, 100,   5]])

In [13]:
np.min(b,axis=1)

array([10, 40,  5])

In [14]:
np.min(b,axis=0)

array([10, 20,  5])

In [15]:
np.max(b,axis=0)

array([ 80, 100,  60])

In [16]:
np.max(b,axis=1)

array([ 30,  60, 100])